### ISSUE TITLE
Did you enable WITH_PTHREADS_PF or WITH_OPENMP for the C++ build?

### ISSUE THREAD

**Issue by nburrus** [died/OpenCvDnnSpeedCompare#2]
Hi, I observed the same performance difference between Python and C++ for the same OpenCV DNN inference. I checked the build information of the python module I installed from conda-forge (with `cv2.getBuildInformation()`) and noticed that it had `Parallel framework: pthreads` while my cmake build did not.

Enabling WITH_PTHEADS_PF or WITH_OPENMP in OpenCV cmake makes the C++ code as fast as the python one on my machine since it can now leverage multiple CPU cores with their parallel_for.

Hope this helps!

**Comment by died** [comment]
Sorry it's long time ago, I think it was default, so many the answer is no ?
